on: workflow_dispatch

name: SNIS_make_repo
jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-44
      options: --privileged
    steps:
    - uses: actions/checkout@v4
    - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
      with:
        bundle: org.flathub.snis
        manifest-path: org.flathub.snis.yml
        cache-key: flatpak-builder-${{ github.sha }}

    - name: See
      run: |   
        ls -l
        ls -l repo
        ls -l ..
    - name: add
      run: git add -a repo
    - name: commit 
      run: git commit -m "commiting" -a 
    - name: push
      run: git push
    - name: fetch from master
      run: git fetch origin master
    - name: push code to master
      run: git push origin HEAD:master      
