on: workflow_dispatch

name: SNIS_make
jobs:
  flatpak:
    name: "Flatpak"
    runs-on: ubuntu-latest
    container:
      image: bilelmoussaoui/flatpak-github-actions:gnome-44
      options: --privileged
    steps:
    - uses: actions/checkout@v4
    - uses: flatpak/flatpak-github-actions/flatpak-builder@v6
      with:
        bundle: org.flathub.snis
        manifest-path: org.flathub.snis.yml
        cache-key: flatpak-builder-${{ github.sha }}

    - name: See
      run: |   
        ls -l
        ls -l repo
        #sudo apt install libfuse2 #required to build AppImage

    - name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: org.flathub.snis 
        path: org.flathub.snis
 
    - name: upload binaries to release
      uses: softprops/action-gh-release@v2
      #if: ${{startsWith(github.ref, 'refs/tags/') }}
      with:
          tag_name: "try_me"
          files: org.flathub.snis
